trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  keyvault: "myvault1920"
  secretName: "dbpass"

steps:
  - task: AzureKeyVault@2
    displayName: "Fetch Secret from Azure Key Vault"
    inputs:
      azureSubscription: "keyvault"
      KeyVaultName: "$(keyvault)"
      SecretsFilter: "$(secretName)"
      RunAsPreJob: false

  - script: |
      echo "Secret fetched successfully"
      echo "Using secret in the application..."
    displayName: "Use Key Vault Secrets"
    env:
      DB_PASSWORD: $(dbpass)